/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package calcular;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class calcular_imc extends javax.swing.JFrame {

    /** Creates new form calcular_imc */
    public calcular_imc() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbg_agrupar = new javax.swing.ButtonGroup();
        jrb_mujeres = new javax.swing.JRadioButton();
        jrb_hombres = new javax.swing.JRadioButton();
        jl_cm = new javax.swing.JLabel();
        jb_nota = new javax.swing.JLabel();
        jb_Peso = new javax.swing.JLabel();
        jb_calcular = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jb_Altura1 = new javax.swing.JLabel();
        jl_kg = new javax.swing.JLabel();
        jl_limpiar = new javax.swing.JButton();
        jl_IMC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbg_agrupar.add(jrb_mujeres);
        jrb_mujeres.setText("mujeres");

        jbg_agrupar.add(jrb_hombres);
        jrb_hombres.setText("hombres");
        jrb_hombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_hombresActionPerformed(evt);
            }
        });

        jl_cm.setText("cm");

        jb_nota.setText("nota:En la altura solo se agrega en centimetros");

        jb_Peso.setText("Peso");

        jb_calcular.setText("calcular");
        jb_calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_calcularMouseClicked(evt);
            }
        });

        jb_Altura1.setText("Altura");

        jl_kg.setText("kg");

        jl_limpiar.setText("limpiar");

        jl_IMC.setText("IMC resultado");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcular/13.jpg"))); // NOI18N
        jLabel1.setIconTextGap(6);
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrb_mujeres)
                        .addGap(109, 109, 109)
                        .addComponent(jrb_hombres)
                        .addContainerGap(544, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jb_Peso))
                            .addComponent(jb_nota)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jb_Altura1)
                                        .addGap(34, 34, 34)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jl_cm))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(186, 186, 186)
                                        .addComponent(jb_calcular))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jl_kg)
                                        .addGap(50, 50, 50))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jl_limpiar)
                                    .addComponent(jl_IMC))
                                .addGap(85, 85, 85)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb_hombres)
                    .addComponent(jrb_mujeres))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_Altura1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_cm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_nota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_Peso)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_kg))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_calcular)
                            .addComponent(jl_limpiar))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_IMC)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_hombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_hombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_hombresActionPerformed

    private void jb_calcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_calcularMouseClicked
        float jTextField3,jtf,jTextField2;
       
       jtf=Float.parseFloat("ingresa tu peso");
       jTextField2=Float.parseFloat("ingresa tu altura");
       jTextField3=jtf/(jTextField2*jTextField2);
       if(jTextField3<=18.5){
           JOptionPane.showMessageDialog(null,"tu IMC es de"+jTextField3+"estas bajo de peso");}
       else if(jTextField3>=18.5&&jTextField3<=25){
           JOptionPane.showMessageDialog(null,"tu IMC es de"+jTextField3+"estas en tu peso");}
       else if(jTextField3>=25&&jTextField3<=30){
           JOptionPane.showMessageDialog(null,"tu IMC es de"+jTextField3+"estas un poco gordo");}
       else if(jTextField3>=30&&jTextField3<=40){
           JOptionPane.showMessageDialog(null,"tu IMC es de"+jTextField3+"estas gordo");}
       else if(jTextField3>=40){
           JOptionPane.showMessageDialog(null,"tu IMC es de"+jTextField3+"estas obeso");}
    }//GEN-LAST:event_jb_calcularMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calcular_imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calcular_imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calcular_imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calcular_imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calcular_imc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel jb_Altura1;
    private javax.swing.JLabel jb_Peso;
    private javax.swing.JButton jb_calcular;
    private javax.swing.JLabel jb_nota;
    private javax.swing.ButtonGroup jbg_agrupar;
    private javax.swing.JLabel jl_IMC;
    private javax.swing.JLabel jl_cm;
    private javax.swing.JLabel jl_kg;
    private javax.swing.JButton jl_limpiar;
    private javax.swing.JRadioButton jrb_hombres;
    private javax.swing.JRadioButton jrb_mujeres;
    // End of variables declaration//GEN-END:variables

}
